config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :dishes, only: [:show]

  mount Cartify::Engine, at: '/'
  root controller: :menus, action: :index
  resources :dishes, only: [:show]
  resource :cart, only: %i[show update]
  resources :order_items, only: %i[create update destroy]
  resources :orders, only: %i[index show]
  resources :checkout

  match 'settings/addresses', to: 'addresses#index', via: 'get'
  match 'settings/addresses', to: 'addresses#create', via: 'post'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
    validates_presence_of :description, :price, :category
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :product, class_name: Cartify.product_class.to_s
    belongs_to :order
    has_one :order_status, through: :order
    has_one :category, through: :product, class_name: Cartify.product_class.to_s

    validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
    validate :product_present
    validate :order_present

    before_save :finalize
    default_scope { order(product_id: :asc) }

    def unit_price
      return self[:unit_price] if persisted?
      product.send(Cartify.price_attribute)
    end

    def total_price
      unit_price * quantity
    end

    private

    def product_present
      errors.add(:product, 'is not valid or is not active.') if product.nil?
    end

    def order_present
      errors.add(:order, 'is not a valid order.') if order.nil?
    end

    def finalize
      self[:unit_price] = unit_price
      self[:total_price] = quantity * self[:unit_price]
    end
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :orders, class_name: 'Cartify::Order', foreign_key: :user_id
         has_one :billing, class_name: 'Cartify::Billing', foreign_key: :user_id
         has_one :shipping, class_name: 'Cartify::Shipping', foreign_key: :user_id
         has_many :addresses, class_name: 'Cartify::Address', foreign_key: :user_id
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper Cartify::Engine.helpers
    include Cartify::CurrentSession
end

app/controllers/checkout_controller.rb
require_dependency 'cartify/application_controller'

module Cartify
  class CheckoutController < Cartify::ApplicationController
    before_action :fast_authentification!
    include Wicked::Wizard
    include Showable
    include Updatable

    steps :login, :addresses, :delivery, :payment, :confirm, :complete

    def show
      return redirect_to main_app.public_send(Cartify.empty_cart_path), notice: "Please add some #{Cartify.product_class.to_s.pluralize(2).downcase} before attempting a checkout" if no_items_in_cart?
      send("show_#{step}") unless step == 'wicked_finish'
      render_wizard
    end

    def update 
        binding.pry
      current_order.update_attribute(:user, current_cartify_user) if current_step?(:addresses) && current_order.respond_to?(:user)
      send("update_#{step}")
      redirect_to next_wizard_path unless performed?
    end

    private

    def no_items_in_cart?
      current_order.order_items.empty? && !current_step?(:complete)
    end

    def current_cartify_user
      send("current_#{Cartify.user_class.name.downcase}".to_sym)
    end
  end
end



#class CheckoutController < ApplicationController
#end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  def show
  end

  def create
    binding.pry
    redirect_to order_items_path, notice: 'Dish is added to the cart!'
  end
  
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @dishes = Dish.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartify/application_helper.rb
module Cartify
    module ApplicationHelper
      def shop_icon_quantity
        qty = current_order.order_items.reload.collect(&:quantity).compact.sum
        unless qty.zero?
          "<span class='shop-quantity shop-icon' id='order-details' title='You have #{pluralize(qty, 'item')} in your order.'>#{pluralize(qty, 'item')}</span>".html_safe
        end
      end
      def active_class(link_path)
        return '' if request.GET.empty?
        link_path.include? request.GET.first.join('=') ? 'active' : ''
      end
      def country_name(object)
        country = ISO3166::Country[object.country]
        country.translations[I18n.locale.to_s] || country.name
      end
      def image_for(obj)
        begin
            obj.image 
        rescue => exception
            'https://vignette.wikia.nocookie.net/teenage-mutant-ninja-turtles-2012-series/images/f/fd/Pizza_trad_pepperoni.png/revision/latest?cb=20161106191944'
        end
      end
    end
end

app/helpers/cartify/carts_helper.rb
module Cartify
    module CartsHelper
      def add_to_cart(dish, qqty = 1, name = 'Add to cart')
        link_to name,
                cartify.order_items_path(order_item: { quantity: qqty, dish_id: dish&.id }),
                method: :post,
                remote: true,
                data: {turbolinks: false}
      end
  
      def checkout_link
        qty = current_order.order_items.reload.collect(&:quantity).compact.sum
        unless qty.zero?
          link_to 'Proceed to checkout', cartify.checkout_path, id: 'checkout-link'
        end
      end
    end
end

app/helpers/cartify/checkout_helper.rb
module Cartify
    module CheckoutHelper
      def active_step?(current_step)
        'active' if current_step == step
      end
      def order_summary_text_position
        return 'text-center general-text-right' if right?
        'general-text-align'
      end
      def order_summary_table_position
        'general-summary-table-right general-text-right' if right?
      end
      private
      def right?
        %i[confirm complete].include? step
      end
    end
end

app/helpers/cartify/order_helper.rb
module Cartify::OrderHelper
    def order_active_filter
      case request.GET[:filter]
      when 'in_progress' then t('order.status.in_progress')
      when 'in_queue' then t('order.status.in_queue')
      when 'in_delivery' then t('order.status.in_delivery')
      when 'delivered' then t('order.status.delivered')
      when 'canceled' then t('order.status.canceled')
      else t('order.status.all')
      end
    end
end

app/views/cartify/addresses/carts/_order_items.haml
- @order_items.each do |order_item|
  %tr
    %td
      .general-img-wrap-table
        = link_to main_app.send("#{Cartify.product_class.to_s.underscore}_path", order_item.product) do
          = image_tag image_for(order_item.product), alt: 'design-book', class: 'cart-img-shadow pull-left'
    %td
      = link_to main_app.send("#{Cartify.product_class.to_s.underscore}_path", order_item.product), class: 'text-as-link' do
        %p.title= order_item.product.send(Cartify.title_attribute)
    %td
      %span.font-16.in-gold-500= number_to_currency(order_item.product.send(Cartify.price_attribute))
    = render 'cartify/carts/quantity', order_item: order_item
    %td
      %span.font-16.in-gold-500= number_to_currency(order_item.total_price)
    %td
      = button_to cartify.order_item_path(order_item), { data: { confirm: "Are you sure you wish to delete the book '#{order_item.product.send(Cartify.title_attribute)}' from your cart?" }, method: :delete, remote: true, class: "close general-cart-close", 'aria-label': 'Close' } do
        %span{'aria-hidden': "true"} &times;

app/views/cartify/addresses/carts/_order_summary.haml
.general-order-wrap
  .row
    .col-sm-4
      .input-group.general-input-group
        = form_tag cart_path, method: :put
        = label_tag :name, t('cart.coupon'), class: 'input-label'
        = text_field_tag(:name, nil, placeholder: t('cart.coupon'), class: 'form-control mb-30')
        %div
          %button.btn.btn-primary.mr-5.mb-15.visible-xs-inline-block= t('cart.apply_coupon')
          = submit_tag t('cart.update'), class: 'btn btn-primary mb-15 res-block'
    .col-sm-8
      .res-mr-200.text-center.general-text-right
        %p.in-gold-500.font-18= t('cart.summary')
        %table.general-summary-table.general-summary-table-right.general-text-right
          = render 'cartify/shared/order_summary_numbers'

app/views/cartify/addresses/carts/_quantity.haml
%td
  .input-group
    = link_to cartify.order_item_path(id: order_item.id, order_item: {quantity: order_item.quantity-1}), class: 'input-link', id: "order_#{order_item.id}_minus", method: :put, remote: true do
      %i.fa.fa-minus.line-height-40 &nbsp;
    %input.form-control.quantity-input{type: 'text', value: order_item.quantity}
    = link_to cartify.order_item_path(id: order_item.id, order_item: {quantity: order_item.quantity+1}), class: 'input-link', id: "order_#{order_item.id}_plus", method: :put, remote: true do
      %i.fa.fa-plus.line-height-40 &nbsp;  

app/views/cartify/addresses/carts/_xs_order_items.haml
- @order_items.each do |order_item|
  .general-cart-item.divider-lg-bottom
    = button_to order_items_path(order_item), { data: { confirm: "Are you sure you wish to delete the book '#{order_item.product.send(Cartify.title_attribute)}' from your cart?" }, method: :delete, remote: true, class: "close general-cart-close", 'aria-label': 'Close' } do
      %span{'aria-hidden': "true"} &times;
    .general-img-wrap-table
      = link_to main_app.send("#{Cartify.product_class.to_s.underscore}_path", order_item.product) do 
        = image_tag image_for(order_item.product), alt: 'design-book', class: 'cart-img-shadow'
    = link_to main_app.send("#{Cartify.product_class.to_s.underscore}_path", order_item.product), class: 'text-as-link' do
      %p.title= order_item.product.send(Cartify.title_attribute)
    %table.table
      %tr
        %td
          %span.in-grey-600= t('cart.price')
        %td
          %span.font-16.in-gold-500= number_to_currency(order_item.product.send(Cartify.price_attribute))
      %tr
        %td.vertical-middle
          %span.in-grey-600= t('cart.quantity')
        = render 'cartify/carts/quantity', order_item: order_item
      %tr
        %td
          %span.in-grey-600= t('cart.subtotal')
        %td
          %span.font-16.in-gold-500= number_to_currency(order_item.total_price)

app/views/cartify/addresses/carts/show.html.haml
%main.container.general-main-wrap
  %h1.general-title-margin= t('cart.cart')
  .visible-xs
    = render 'cartify/carts/xs_order_items', locals: @order_items
  .hidden-xs
    %table.table.table-hover
      %thead
        %tr
          %th.col-pic.pl-0
            %span.in-grey-600= t('cart.product')
          %th.col-title
          %th.col-price
            %span.in-grey-600= t('cart.price')
          %th.col-quantity
            %span.in-grey-600= t('cart.quantity')
          %th.col-total
            %span.in-grey-600= t('cart.subtotal')
          %th.col-close
      = render 'cartify/carts/order_items', locals: @order_items
  = render 'cartify/carts/order_summary'
  .text-center
    = link_to t('cart.checkout'), checkout_index_path, class: 'btn btn-default mb-20'

app/views/cartify/addresses/index.haml
%main.container
  %h1.general-title-margin= t('settings.settings')
  %ul.nav.clearfix.mb-20{role: "tablist"}
    %li.tab-item{role: "presentation"}
      = link_to t('settings.address'), settings_addresses_path, class: 'tab-link filter-link active'
    %li.tab-item{role: "presentation"}
      = link_to t('settings.privacy'), 'settings_privacy_path', class: 'tab-link'
  .tab-content
    = render 'cartify/shared/addresses_form'
    

app/views/cartify/checkout/_order_summary.haml
%div{ class: order_summary_text_position }
  %p.in-gold-500.font-18= t('cart.summary')
  %table.general-summary-table{ class: order_summary_table_position }
    = render 'cartify/shared/checkout_summary_numbers', current_order: current_order

app/views/cartify/checkout/_progress.haml
%nav{aria: {label: "breadcrumb"}}
  %ol.steps.breadcrumb
    %li.breadcrumb-item.clickable-step{ class: active_step?(:addresses), 'data-href': wizard_path(:addresses) }
      %span.step-number 1
      %span.step-text.hidden-xs= t('settings.address')
    %li.breadcrumb-item.clickable-step{ class: active_step?(:delivery), 'data-href': wizard_path(:delivery) }
      %span.step-number 2
      %span.step-text.hidden-xs=t('confirm.delivery')
    %li.breadcrumb-item.clickable-step{ class: active_step?(:payment), 'data-href': wizard_path(:payment) }
      %span.step-number 3
      %span.step-text.hidden-xs=t('confirm.paymant')
    %li.breadcrumb-item.clickable-step{ class: active_step?(:confirm), 'data-href': wizard_path(:confirm) }
      %span.step-number 4
      %span.step-text.hidden-xs=t('confirm.confirm')
    %li.breadcrumb-item.clickable-step{ class: active_step?(:complete), 'data-href': wizard_path(:complete) }
      %span.step-number 5
      %span.step-text.hidden-xs=t('confirm.complete')

app/views/cartify/checkout/addresses.haml
%main.container
  = render 'cartify/checkout/progress'
  = form_for @addresses, url: wizard_path, method: :put, class: 'res-mb-100' do |f|
    .row
      .col-md-5.mb-40
        .visible-xs.visible-sm
          %h3.general-subtitle= t('settings.billing')
          %p.general-info-text 
            %small all fields are required
        = f.fields_for @addresses.billing do |ff|
          - bill_errors = @addresses.billing.errors
          = render 'cartify/shared/address', ff: ff, errors: bill_errors
          = f.hidden_field "[billing][order_id]", value: current_order.id
      .col-md-5.col-md-offset-1.mb-60
        .visible-xs.visible-sm
          %h3.general-subtitle= t('settings.shipping')
          %p.general-info-text 
            %small all fields are required
        = f.fields_for @addresses.shipping do |ff|
          - ship_errors = @addresses.shipping.errors
          = render 'cartify/shared/address', ff: ff, errors: ship_errors
          = f.hidden_field "[shipping][order_id]", value: current_order.id
        .form-group.checkbox
          %label.checkbox-label
            = f.check_box :use_billing, class: 'checkbox-input', id: 'use_billing', hidden: true
            %span.checkbox-icon
              %i.fa.fa-check
            %span.checkbox-text= t('settings.use_billing')
    .general-text-align.mb-60
      = render 'cartify/checkout/order_summary'
      = f.submit t('checkout.save_and_continue'), class: 'btn btn-default center-block mb-20'

app/views/cartify/checkout/complete.haml
%main.container.general-main-wrap
  = render 'cartify/checkout/progress'
  .text-center.mb-40
    %h3.general-subtitle= t('complete.thanks')
    %p.fw-300= t('complete.has_been_sent_to') + @order.user.email.capitalize
  .row.mb-20
    .col-sm-6
      .visible-xs
        %p.general-order-number.mb-0= @order.sharp_number
        %p.general-address.mb-30= @order.creation_date
      = render 'cartify/checkout/partials/addresses_short', address: @order.shipping
    .col-sm-6.hidden-xs.text-right
      %p.general-order-number.mb-0= @order.sharp_number
      %p.general-address.mb-30= @order.creation_date
  = render 'cartify/checkout/partials/list_of_items', current_order: @order
  .mb-55
    = render 'cartify/checkout/order_summary', current_order: @order
    .text-center
      = link_to t('button.back_to_store'), next_wizard_path, class: 'btn btn-default mb-20'

app/views/cartify/checkout/confirm.haml
%main.container.general-main-wrap
  = render 'cartify/checkout/progress'
  .row.mb-20
    .col-sm-3
      %h3.general-subtitle= t('settings.shipping')
      = render 'cartify/checkout/partials/addresses_short', address: @addresses.shipping
    .col-sm-3
      %h3.general-subtitle= t('settings.billing')
      = render 'cartify/checkout/partials/addresses_short', address: @addresses.billing
    .col-sm-3
      %h3.general-subtitle= t('confirm.shipments')
      %p.general-address
        = current_order.delivery.name
        %span.general-edit.clickable-step{ 'data-href': wizard_path(:delivery) }=t('confirm.edit')
        %br
        = current_order.delivery.duration
    .col-sm-3
      %h3.general-subtitle= t('confirm.payment_info')
      %p.general-address
        = current_order.secret_card_number
        %span.general-edit.clickable-step{ 'data-href': wizard_path(:payment) }=t('confirm.edit')
        %br
        = current_order.credit_card.mm_yy
  / = render 'cartify/checkout/partials/list_of_items'
  = render 'cartify/checkout/order_summary'
  .text-center
    = button_to t('checkout.place_order'), wizard_path, method: :put, class: 'btn btn-default mb-20'

app/views/cartify/checkout/delivery.haml
%main.container.general-main-wrap
  = render 'cartify/checkout/progress'
  %h3.general-subtitle= t('delivery.delivery_method')
  = form_for current_order, url: wizard_path do |f|
    .visible-xs
      = render 'cartify/checkout/partials/delivery-xs', f: f if false
    .hidden-xs.mb-res-50
      = render 'cartify/checkout/partials/delivery-lg', f: f
    = render 'cartify/checkout/order_summary'
    .text-center
      = f.submit t('checkout.save_and_continue'), class: 'btn btn-default mb-20', disabled: true

app/views/cartify/checkout/login.haml
%main.container.general-main-wrap
  .hidden-xs.hidden-sm
    .row
      .col-md-5.mb-40
        .visible-xs.visible-sm
        - if main_app.respond_to?(:user_facebook_omniauth_authorize_path)
          .text-center
            %h3.general-subtitle.mt-0= t('checkout.returning_customer')
            %a.general-login-icon{ href: main_app.user_facebook_omniauth_authorize_path }
              %i.fa.fa-facebook-official
            %p.general-login-text= t('checkout.or')
        = form_with url:  main_app.user_session_path, scope: :user, local: true, class: 'general-form' do |f|
          .form-group.mb-40
            %p.fw-600= t('checkout.login_with_password')
            = f.label :email, t('checkout.enter_email'), class: 'control-label input-label', for: :login_email
            = f.email_field :email, placeholder: t('checkout.enter_email'), autofocus: true, class: 'form-control', id: :login_email
          .form-group.mb-40
            = f.label :password, t('settings.password'), class: 'control-label input-label', for: :login_password
            = f.password_field :password, placeholder: t('settings.password'), class: 'form-control', id: :login_password
            %a.help-block.in-gold-500{ href:  main_app.new_user_password_path }= t('button.forgot_password')
          .text-left
          = f.submit t('checkout.login_with_password'), class: 'button btn btn-default mb-20'
      .col-md-5.mb-40
        .visible-xs.visible-sm
        - if main_app.respond_to?(:user_facebook_omniauth_authorize_path)
          .text-center
            %h3.general-subtitle.mt-0= t('checkout.new_customer')
            %a.general-login-icon{href:  main_app.user_facebook_omniauth_authorize_path}
              %i.fa.fa-facebook-official
            %p.general-login-text= t('checkout.or')
        = form_with url:  main_app.user_registration_path, scope: :user, local: true, class: 'general-form' do |f|
          .form-group.mb-40
            %p.fw-600= t('checkout.quick_register')
            %p.fw-300= t('checkout.quick_description')
            = f.label :email, t('checkout.enter_email'), class: 'control-label input-label'
            = f.email_field :email, placeholder: t('checkout.enter_email'), class: 'form-control'
            - password = Devise.friendly_token.first(10) + '1zZ'
            = f.hidden_field :password, value: password
            = f.hidden_field :password_confirmation, value: password
          .text-left
          = f.submit t('checkout.continue'), class: 'button btn btn-default mb-20'

app/views/cartify/checkout/partials/_addresses_short.haml
%p.general-address
  = address.first_name + ' ' + address.last_name
  - if step != :complete
    %span.general-edit.clickable-step{ 'data-href': wizard_path(:addresses) }=t('confirm.edit')
  %br
  = address.address
  %br
  = address.city + ' ' + address.zip.to_s
  %br
  = country_name address
  %br
  = 'Phone ' + address.phone

app/views/cartify/checkout/partials/_delivery-lg.haml
%table.table.table-hover
  %thead
    %tr
      %th.col-method
        %span.in-grey-600.ml-40= t('delivery.method')
      %th
        %span.in-grey-600= t('delivery.days')
      %th
        %span.in-grey-600= t('delivery.price')
  %tbody
    = f.hidden_field :delivery_id
    - @deliveries.each do |delivery| 
      %tr.delivery-row{data:{delivery: delivery.id}}
        %td
          %span= delivery.name
        %td
          %span= delivery.duration
        %td
          %span.font-16.in-gold-500= number_to_currency delivery.price

app/views/cartify/checkout/partials/_delivery-xs.haml
= f.collection_radio_buttons :delivery_id, @deliveries, :id, :name do |b|
  .general-cart-item.divider-lg-bottom
    %table.table
      %tr
        %td.col-half
          %span.in-grey-600= t('delivery.method')
        %td.col-half
          .form-group.radio.mt-0.mb-0
            = b.label(class: 'radio-label') do
              = b.radio_button(class: 'radio-input')
              %span.radio-icon
              %span.radio-text= b.text
      %tr
        %td
          %span.in-grey-600= t('delivery.days')
        %td
          %span.font-16.fw-300= b.object.duration
      %tr
        %td
          %span.in-grey-600= t('delivery.price')
        %td
          %span.font-16.in-gold-500= number_to_currency b.object.price

app/views/cartify/checkout/partials/_list_of_items.haml
.visible-xs
  - current_order.order_items.each do |item|
    .general-cart-item.divider-lg
      .general-img-wrap-table
        = link_to main_app.send("#{Cartify.product_class.to_s.underscore}_path", item.product) do
          = image_tag image_for(item.product), alt: 'design-book', class: 'cart-img-shadow'
      %p.title= item.product.send(Cartify.title_attribute)
      - if item.product.respond_to?(:description)
        %p.in-grey-600.fw-300= item.product.description.split('. ').first + '.'
      %table.table
        %tr
          %td
            %span.in-grey-600= t('cart.price')
          %td
            %span.font-16.in-gold-500= number_to_currency item.product.send(Cartify.price_attribute)
        %tr
          %td.vertical-middle
            %span.in-grey-600= t('cart.quantity')
          %td
            %span= item.quantity
        %tr
          %td
            %span.in-grey-600= t('order.total')
          %td
            %span.font-16.in-gold-500= number_to_currency item.total_price
.hidden-xs.divider-lg.pt-20
  %table.table.table-hover
    %thead
      %tr
        %th
          %span.in-grey-600= Cartify.product_class.to_s
        %th.col-method
        %th
          %span.in-grey-600= t('cart.price')
        %th
          %span.in-grey-600= t('cart.quantity')
        %th
          %span.in-grey-600= t('order.total')
    %tbody
      - current_order.order_items.each do |item|
        %tr
          %td
            .general-img-wrap-table
              = link_to main_app.send("#{Cartify.product_class.to_s.underscore}_path", item.product) do
                = image_tag image_for(item.product), alt: 'design-book', class: 'pull-left'
          %td
            = link_to main_app.send("#{Cartify.product_class.to_s.underscore}_path", item.product), class: 'text-as-link' do
              %p.title= item.product.send(Cartify.title_attribute)
            - if item.product.respond_to?(:description)
              %p.in-grey-600.fw-300= item.product.description.split('. ').first + '.'
          %td
            %span.font-16.in-gold-500= number_to_currency item.product.send(Cartify.price_attribute)
          %td
            %span.ml-30= item.quantity
          %td
            %span.font-16.in-gold-500= number_to_currency item.total_price

app/views/cartify/order_items/create.js.erb
<% if current_order.errors.any? || @order_item.errors.any? %>
  alert('You order is not valid!')
<% else %>
  var element = document.getElementById('order-details')
  var checkoutButton = document.getElementById('checkout-link')
  var message = "<%= pluralize(current_order.order_items.reload.collect(&:quantity).compact.sum, 'item') %>"
  if (element === null) {
    element = document.createElement('span');
    element.className = 'shop-quantity'
    element.id = 'order-details'
    element.title = message
    document.body.insertBefore(element, document.body.firstChild);
    tippy(element)
  }
  if (checkoutButton === null) {
    reload();
  }
  clearNotifications();
  element.innerHTML = message;
  element._tippy.popper.querySelector('.tippy-content').textContent = `You have ${message} in your order`
<% end %>

app/views/cartify/orders/_filters.haml
%a.dropdown-toggle.lead.small{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}
  = order_active_filter
  %i.fa.fa-angle-down.dropdown-icon.pull-right
%ul.dropdown-menu
  %li
    = link_to t('order.status.in_queue'), orders_path(filter: :in_queue)
  %li
    = link_to t('order.status.in_progress'), orders_path(filter: :in_progress)
  %li
    = link_to t('order.status.in_delivery'), orders_path(filter: :in_delivery)
  %li
    = link_to t('order.status.delivered'), orders_path(filter: :delivered)
  %li
    = link_to t('order.status.canceled'), orders_path(filter: :canceled)
  %li
    = link_to t('order.status.all'), orders_path

app/views/cartify/orders/show.haml
%main.container.general-main-wrap
  =link_to orders_path, class: 'general-back-link' do
    %i.fa.fa-long-arrow-left.mr-15
    = t('button.back_to_orders')
  .row.mb-20
    .col-sm-3
      %h3.general-subtitle= t('settings.shipping')
      = render 'cartify/checkout/partials/addresses_short', address: @order.shipping, step: :complete
    .col-sm-3
      %h3.general-subtitle= t('settings.billing')
      = render 'cartify/checkout/partials/addresses_short', address: @order.billing, step: :complete
    .col-sm-3
      %h3.general-subtitle= t('confirm.shipments')
      %p.general-address
        = @order.delivery.name
        %br
        = @order.delivery.duration
    .col-sm-3
      %h3.general-subtitle= t('confirm.payment_info')
      %p.general-address
        = @order.secret_card_number
        %br
        = @order.credit_card.mm_yy
  = render 'cartify/checkout/partials/list_of_items', current_order: @order
  %div.text-center.general-text-right
    %p.in-gold-500.font-18= t('cart.summary')
    %table.general-summary-table.general-summary-table-right.general-text-right
      = render 'cartify/shared/checkout_summary_numbers', current_order: @order, step: :comfirm

app/views/cartify/shared/_addresses_form.haml
#addres.general-main-wrap.tab-pane.fade.in.active{role: "tabpanel"}
  = form_for @addresses, url: settings_addresses_path do |f|
    .hidden-xs.hidden-sm
      .row
        .col-md-5
          %h3.general-subtitle.mt-0= t('settings.billing')
        .col-md-5.col-md-offset-1
          %h3.general-subtitle.mt-0= t('settings.shipping')
    .row
      .col-md-5.mb-40
        .visible-xs.visible-sm
          %h3.general-subtitle.mt-0= t('settings.billing')
        = f.fields_for @addresses.billing do |ff|
          - bill_errors = @addresses.billing.errors
          = render 'cartify/shared/address', ff: ff, errors: bill_errors
          = f.hidden_field "[billing][user_id]", value: cartify_current_user.id
      .col-md-5.col-md-offset-1.mb-25
        .visible-xs.visible-sm
          %h3.general-subtitle.mt-0= t('settings.shipping')
        = f.fields_for @addresses.shipping do |ff|
          - ship_errors = @addresses.shipping.errors
          = render 'cartify/shared/address', ff: ff, errors: ship_errors
          = f.hidden_field "[shipping][user_id]", value: cartify_current_user.id
        .form-group.checkbox
          %label.checkbox-label
            = f.check_box :use_billing, class: 'checkbox-input', id: 'use_billing', hidden: true
            %span.checkbox-icon
              %i.fa.fa-check
            %span.checkbox-text= t('settings.use_billing')
    .ral-text-align.mb-60
      = f.submit t('settings.save'), class: 'button btn btn-default center-block mb-20'